[app]

app-server ansible_host=18.206.90.107

[monitoring-server]

monitoring ansible_host=44.201.74.95

[all:vars]

ansible_user=ubuntu
ansible_ssh_private_key_file=./projkey.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'